### ISSUE TITLE
1.0.4 has a bug

### ISSUE THREAD

**Issue by xueweiyema** [Akryum/vue-tooltip#2]
ERROR in ./~/v-tooltip/dist/v-tooltip.js
Module not found: Error: Cannot resolve module 'Tooltip' in xxxxxxxxxx\node_modules\v-tooltip\dist
 @ ./~/v-tooltip/dist/v-tooltip.js 1:97-115

I uninstall 1.0.4 and re-install 1.0.0.  it works.

**Comment by Akryum** [comment]
How is your `import` statement?

**Comment by xueweiyema** [comment]
Hello,
import VTooltip from 'v-tooltip'
Vue.use(VTooltip);

**Comment by xueweiyema** [comment]
Now , I use npm install --save vue-tooltip@1.0.0

**Comment by Akryum** [comment]
Could you try `import VTooltip from 'v-tooltip/src'`?

**Comment by xueweiyema** [comment]
I try it, I still can't make it work.
`import VTooltip from 'v-tooltip/src'`
`Vue.use(VTooltip)`

```
ERROR in ./src/home/home.js
Module not found: Error: Cannot resolve module 'v-tooltip/src' in D:\Excellent\frontend\ciibi\src\home
 @ ./src/home/home.js 23:11-35
```

**Comment by Akryum** [comment]
What's the list of files in `node_modules/v-tooltip` and the result of `npm list`?

**Comment by ChrisTerBeke** [comment]
Same issue here. 1.0.0 works perfectly, later versions give an error:

```
Module not found: Error: Cannot resolve module 'Tooltip' in ./node_modules/v-tooltip/dist
```

**Comment by Akryum** [comment]
Since the `theter`, `tether-drop` and `tether-tooltip` packages are not bundled in the compiled dist file, you have to include them in the page: [jsfiddle](https://jsfiddle.net/Akryum/tsjco74e/)
But these are declared as dependencies and should be installed alongside `v-tooltip`, so if you import the source file in the npm package, `import VTooltip from 'v-tooltip/src/index.js'`, it should work.

Please post you `npm list` and your setup (are you using webpack? browserify? etc.) here if you are still facing the issue.

**Comment by dweldon** [comment]
I tried `import VTooltip from 'v-tooltip/src/index.js'` and that didn't work. I suspect this is a webpack issue. If you create a new [webpack-boilerplate](https://github.com/vuejs-templates/webpack) project, accept the defaults, and attempt to use this package you'll get the error.

**Comment by xueweiyema** [comment]
1.0.5 is excellent ! It fixs this bug!
